name: Deploy on environment

on:
  push:
    branches:
      - dev
    paths-ignore:
      - ".gitignore"
      - "docker-compose.yml"
      - "*.md"
      - '.github/**/*.yml'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v4
    - run: echo $SSH_HOST

#    - name: Get changed files
#      id: changed-files
#      uses: tj-actions/changed-files@v35
#      with:
#        since_last_remote_commit: true
#        separator: ","
#
#    - name: copy file via ssh password
#      uses: appleboy/scp-action@v0.1.7
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        key: ${{ secrets.KEY }}
#        source: "tests/a.txt,tests/b.txt"
#        target: your_server_target_folder_path



#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3

#      - name: Build and push
#        uses: docker/build-push-action@v5
##        if:
#        with:
#          push: true #${{ github.event_name == 'push.tags' }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}

#      - name: Start Deployment
#        uses: TapTap21/docker-remote-deployment-action@v1.1
#        with:
#          remote_docker_host: ec2-user@ec2-34-246-134-80.eu-west-1.compute.amazonaws.com
#          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
#          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
#          stack_file_name: docker-compose.yml
#          docker_login_password: ${{ secrets.DOCKER_REPO_PASSWORD }}
#          docker_login_user: ${{ secrets.DOCKER_REPO_USERNAME }}
#          docker_login_registry : ${{ steps.login-ecr.outputs.registry }}
#          args: -p myapp up -d
#
#      - name: executing remote ssh commands using password
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
#          script: |
#            scp