name: Build Docker Image and Push to DockerHub

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "docker-compose.yml"
      - "*.md"
#      - '.github/**/*.yml'

#  pull_request:
#    branches:
#      - main
#    tags:
#      - "*.*.*"
#    paths-ignore:
#      - ".gitignore"
#      - "docker-compose.yml"
#      - "*.md"

jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.3.20
        with:
          package-path: ./package.json

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        if: steps.create_tag.outputs.successful
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          #filter: (^[\s]+?[R|r]elease)|(^[R|r]elease)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: jaywcjlove/create-tag-action@main
        if: steps.create_tag.outputs.successful
        with:
          version: ${{steps.create_tag.outputs.version}}
          release: true
          body: |
            ```bash
            docker pull fusiontwin/dt-be:${{steps.changelog.outputs.version}}
            ```            
            ${{ steps.changelog.outputs.compareurl }}
            ${{ steps.changelog.outputs.changelog }}

  tags:
    runs-on: ubuntu-latest
    steps:

      - name: Get Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images:
#            ghcr.io/fusiontwin/dt-be
            fusiontwin/dt-be
          tags: |
            type=semver,pattern={{version}}
            type=edge,enable=true,priority=700,prefix=,suffix=,branch=dev
#            type=sha,prefix={{branch}}-
#            type=sha,enable=true,priority=100,prefix=sha-,suffix=
#            type=semver,pattern={{major}}.{{minor}},enable=${{ matrix.base == 'debian' }}
#            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

#          labels: |
#            org.opencontainers.image.title=dtwin-backend
#            org.opencontainers.image.description=Digital Twin Backend
#            org.opencontainers.image.vendor=Next Step Fusion
          flavor: |
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
#        if:
        with:
          push: true #${{ github.event_name == 'push.tags' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}