name: Build Docker Image and Push to DockerHub

on:
  push:
    branches:
      - dev
    tags:
      - "*.*.*"
    paths-ignore:
      - ".gitignore"
      - "docker-compose.yml"
      - "*.md"
#  pull_request:
#    branches:
#      - main
#    tags:
#      - "*.*.*"
#    paths-ignore:
#      - ".gitignore"
#      - "docker-compose.yml"
#      - "*.md"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images:
#            ghcr.io/fusiontwin/dt-be
            fusiontwin/dt-be
          tags: |
            type=semver,pattern={{version}},enable=${{ matrix.base == 'debian' }}
            type=edge,enable=true,priority=700,prefix=,suffix=,branch=dev
#            type=sha,prefix={{branch}}-
#            type=sha,enable=true,priority=100,prefix=sha-,suffix=
#            type=semver,pattern={{major}}.{{minor}},enable=${{ matrix.base == 'debian' }}
#            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

          labels: |
            org.opencontainers.image.title=dtwin-backend
            org.opencontainers.image.description=Digital Twin Backend
            org.opencontainers.image.vendor=Next Step Fusion
          flavor: |
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name = 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}